### ISSUE TITLE
Error running Rspec/FactoryGirl after updating from 0.7.4 to 0.7.5

### ISSUE THREAD

**Issue by Tonkpils** [diogob/activerecord-postgres-hstore#85]
Updating gem from 0.7.4 to 0.7.5 causes all my tests to break. Specifically on the Factory for the model that has the hstore attribute

``` ruby
let(:first_box) { create(:box, client_id: client.id) }
     NoMethodError:
       undefined method `to_hstore' for {}:Hash
```

``` ruby
FactoryGirl.define do
  factory :box do
    client_id 1
    friendly_name { Faker::Name.name }
  end
end
```

The attribute for the `box` model is called `metadata`. I'm a bit confused because I'm not using `to_hstore` anywhere. The tests pass just fine using this gem's version `0.7.4`. When I updated to 0.7.5 the tests started failing.
